version: '3.8'

services:  
  db:
    container_name: pg_container
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: test_db
    networks:
      docker_network_custom:
        ipv4_address: 172.19.1.1
    ports:
      - "5432:5432"
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: 123456
    networks:
      docker_network_custom:
        ipv4_address: 172.19.1.2
    ports:
      - "5050:80"

networks:
  docker_network_custom:
    ipam:
      driver: default
      config:
        - subnet: 172.19.0.0/16
